# basic options
title: Demo Portal for Wiki Replacement
author: GitHub User
email: francis.ferguson@lumen.com
description: Network Documentation

# Build settings
markdown: kramdown
defaults:
remote_theme: minina
  -
    scope:
      path: ""
    values:
      layout: "posts"

permalink: "/:categories/:title"
