# basic options
title: demo Site for Wiki Replacement
author: GitHub User
email: francis.ferguson@lumen.com
description: Network Documentation 

# Build settings
markdown: kramdown
theme: minima
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "posts"
