# basic options
title: Demo Portal for Wiki Replacement
author: GitHub User
email: francis.ferguson@lumen.com
description: Network Documentation

# Build settings
markdown: kramdown
theme: minina
permalink: /:categories/:title/
baseurl: /demo-wiki
imclude: /_pages
